spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: portfolioBackOfficeProject
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          schema_generation:
            script:
              action: create
              create-target: ddl.sql